// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTkMoA_isWdZkCr_S3a34br8y0rXSdzn0',
    appId: '1:685189244089:web:c660f75768c1a47289e768',
    messagingSenderId: '685189244089',
    projectId: 'crypto-list-flutter-app',
    authDomain: 'crypto-list-flutter-app.firebaseapp.com',
    storageBucket: 'crypto-list-flutter-app.appspot.com',
    measurementId: 'G-F0W3BM9FSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88EnGqvaN6g8M_ihWv1zAwXn9YuP_hgk',
    appId: '1:685189244089:android:07a37d085a45388a89e768',
    messagingSenderId: '685189244089',
    projectId: 'crypto-list-flutter-app',
    storageBucket: 'crypto-list-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRi5DvutMBPB1VcumekWKVbnQflekBYI',
    appId: '1:685189244089:ios:dceaeaeb0e37c55089e768',
    messagingSenderId: '685189244089',
    projectId: 'crypto-list-flutter-app',
    storageBucket: 'crypto-list-flutter-app.appspot.com',
    iosClientId: '685189244089-6nh7if4aq3pd1mcum5qst9ff5f1ljbkm.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRi5DvutMBPB1VcumekWKVbnQflekBYI',
    appId: '1:685189244089:ios:dceaeaeb0e37c55089e768',
    messagingSenderId: '685189244089',
    projectId: 'crypto-list-flutter-app',
    storageBucket: 'crypto-list-flutter-app.appspot.com',
    iosClientId: '685189244089-6nh7if4aq3pd1mcum5qst9ff5f1ljbkm.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );
}
